# Generated by Django 4.2.4 on 2023-08-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompanyApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.jobprofile')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.userapi')),
            ],
        ),
    ]
