# Generated by Django 4.2.4 on 2023-08-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_jobprofile_usercompanyapi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCompanyApi',
            new_name='UserCompanyApiModel',
        ),
    ]
